apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route
spec:
  parentRefs:
    - name: nuagir-gateway-service
  hostnames:
    - "jfmainville.me"
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: my-site-cip-service
          port: 3000
